######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 18 19:23:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += core network gui

# Input
HEADERS += msg.h qchat.h
FORMS += qchat.ui
SOURCES += main.cpp qchat.cpp
